zenml-io/zenml-projects

.github/workflows/pull_request.yml, nba-pipeline/Building and Using An MLOPs Stack With ZenML.ipynb, nba-pipeline/README.md, nba-pipeline/steps/feature_engineer.py, nba-pipeline/steps/importer.py
- Added codespell CI workflow
- Fixed spellings
=> Add codespell spell checking

Powerful DQN/GameWrap.py, Powerful DQN/agent.py, Powerful DQN/replay_buffer.py, Powerful DQN/train_dqn.py
=> Add the Powerful DQN 

nba-pipeline/README.md
Added some minor changes and fixed some alignment problem
=> Updated README

customer-satisfaction/README.md, customer-satisfaction/pipelines/deployment_pipeline.py, customer-satisfaction/pipelines/training_pipeline.py, customer-satisfaction/streamlit_app.py
I definitely feel like we need to imprve this a bit more but i am making this PR now for early feedback :-)
=> Update readme customer satisfaction

customer-satisfaction/pipelines/deployment_pipeline.py, customer-satisfaction/requirements.txt, customer-satisfaction/run_deployment.py, customer-satisfaction/run_pipeline.py
made it compatible with newest version
=> added mlflow deployment updates

customer-satisfaction/requirements.txt, customer-satisfaction/run_deployment.py, customer-satisfaction/run_pipeline.py, customer-satisfaction/streamlit_app.py
Made compatible with latest version.  
Changes, 
Upgraded the Zenfile MLflow tracker to 0.7.3
=> Update to new Version 

README.md
Added customer churn to the main readme zenfile tables
=> Added customer churn to the main readme zenfile tables 

customer-satisfaction/README.md, nba-pipeline/Building and Using An MLOPs Stack With ZenML.ipynb, nba-pipeline/README.md
Replace `--type` with `--flavor` inside the ZenFiles to comply with the changes coming in the next release
=> Changing `--type` to `--flavor` to prepare for the next release

README.md
Added stack components column as suggested by Hamza
=> Added stack components

customer-satisfaction/README.md, customer-satisfaction/pipelines/deployment_pipeline.py, customer-satisfaction/requirements.txt, customer-satisfaction/run_deployment.py
This PR updates the customer-satisfaction ZenFile to work with the latest version of zenml.
=> Update customer-satisfaction ZenFile to work with zenml==0.10.0

customer-churn/README.md, customer-churn/run_seldon_deployment_pipeline.py
Fixed ZenFiles bringing them in line with the new CLI changes (see [here](https://github.com/zenml-io/zenml/pull/833) for more).
THIS SHOULD NOT BE MERGED UNTIL WE MAKE THE NEXT RELEASE.
=> Update ZenFiles to account for new CLI commands

customer-satisfaction/README.md, customer-satisfaction/config.yaml, customer-satisfaction/materializer/custom_materializer.py, customer-satisfaction/pipelines/deployment_pipeline.py, customer-satisfaction/pipelines/training_pipeline.py, customer-satisfaction/requirements.txt, customer-satisfaction/run_deployment.py, customer-satisfaction/run_pipeline.py, customer-satisfaction/steps/config.py, customer-satisfaction/steps/evaluation.py, customer-satisfaction/steps/model_train.py
Update the custom satisfaction ZenFile to work with ZenML 0.20.2!
Please ensure you have done the following:
=> Update Customer Satisfaction to ZenML 0.20.2

.codespell-ignore-words, .github/workflows/markdown-link-check.yml, .github/workflows/markdown_check_config.json, .github/workflows/pull_request.yml, README.md, atari-game-play/README.md
This PR adds the necessary files to create a GitHub actions workflow for the markdown link checker. Also fixes 2 broken links.
=> Github Actions - Link Checker

sign-language-detection-yolov5/README.md
=> Minor README updates

orbit-user-analysis/pipelines/community_analysis_pipeline.py, orbit-user-analysis/requirements.txt, orbit-user-analysis/run.py, orbit-user-analysis/steps/booming.py, orbit-user-analysis/steps/churned.py, orbit-user-analysis/steps/report.py, orbit-user-analysis/steps/utils.py
The Orbit pipeline now uses the new ZenML version (0.40.2) with the new pipeline API, the connectors, and the newly centralized secret store.
=> Finalizing the Orbit project

CONTRIBUTING.md, README.md, customer-churn/README.md, customer-churn/pipelines/seldon_deployment_pipeline.py, customer-satisfaction/README.md, langchain-llamaindex-slackbot/README.md, langchain-qa-hub/README.md, langchain-qa-hub/langchain-qa-hub.ipynb, nba-pipeline/README.md, nba-pipeline/pipelines/prediction_pipeline.py, nba-pipeline/steps/feature_engineer.py, nba-pipeline/steps/predictor.py, orbit-user-analysis/README.md, sign-language-detection-yolov5/README.md, supabase-openai-summary/README.md, supabase-openai-summary/src/run.py, time-series-forecast/README.md, zen-news-summarization/README.md
=> Fixing the links to our documentation page after the major update

customer-satisfaction/model/evaluation.py, customer-satisfaction/run_deployment.py, langchain-llamaindex-slackbot/scripts/production_deploy.sh, langchain-llamaindex-slackbot/src/chat_lanarky.py, langchain-llamaindex-slackbot/src/constants.py, langchain-llamaindex-slackbot/src/main.py, langchain-llamaindex-slackbot/src/pipelines/index_builder.py, langchain-llamaindex-slackbot/src/run.py, langchain-llamaindex-slackbot/src/slackbot_utils.py, langchain-llamaindex-slackbot/src/steps/url_scraper.py, langchain-llamaindex-slackbot/src/steps/web_url_loader.py, langchain-qa-hub/run.py, nba-pipeline/run_pipeline.py, nba-pipeline/steps/analyzer.py, nba-pipeline/steps/discord_bot.py, nba-pipeline/steps/drift_reporter.py, nba-pipeline/steps/utils.py, orbit-user-analysis/constants.py, orbit-user-analysis/pipelines/community_analysis_pipeline.py, orbit-user-analysis/run.py, orbit-user-analysis/steps/booming.py, orbit-user-analysis/steps/churned.py, orbit-user-analysis/steps/report.py, orbit-user-analysis/steps/utils.py, sign-language-detection-yolov5/model.py, supabase-openai-summary/src/run.py, supabase-openai-summary/src/steps/importers.py, supabase-openai-summary/src/steps/summarizers.py, zen-news-summarization/src/zennews/cli/sources.py
- made some tweaks to improve the answer quality of the bot (mainly around which data gets used, but also upgraded from gpt3.5 -> 4 and bumping the `temperature` param to 1 (from 0))
- ran the formatting script on the entire repo (so anything outside the `/langchain-llamaindex-slackbot` folder was autofixes by `ruff` from that)
- add a script that (re)deploys both bots
=> Improve slackbot answer quality

.gitignore, llm-complete-guide/run.py, llm-complete-guide/steps/eval_retrieval.py, llm-complete-guide/steps/eval_visualisation.py, llm-complete-guide/steps/populate_index.py, llm-complete-guide/utils/llm_utils.py
Some small updates and fixes ahead of the RAG webinar.
=> LLM RAG webinar updates

llm-lora-finetuning/requirements.txt
Restore requirements for LoRa project
=> Restore requirements for LoRa

end-to-end-computer-vision/.dockerignore, end-to-end-computer-vision/.gitignore, end-to-end-computer-vision/configs/inference_pipeline.yaml, end-to-end-computer-vision/configs/ingest_data.yaml, end-to-end-computer-vision/configs/training_pipeline_remote_eks_example.yaml, end-to-end-computer-vision/data/.gitignore, end-to-end-computer-vision/data/README.md, end-to-end-computer-vision/materializers/ultralytics_materializer.py, end-to-end-computer-vision/materializers/yolo_materializer.py, end-to-end-computer-vision/pipelines/training.py, end-to-end-computer-vision/requirements.txt, end-to-end-computer-vision/steps/export_label_studio.py, end-to-end-computer-vision/steps/fiftyone_inference.py, end-to-end-computer-vision/steps/train_model.py
Added examples of how to use aws/eks/s3 instead gcp. Fixed issues where the train_model step was failing to save the new weights of the model post training.
=> computer vision project improvments. 

llm-complete-guide/constants.py, llm-complete-guide/notebooks/argilla_embeddings.ipynb, llm-complete-guide/pipelines/distilabel_generation.py, llm-complete-guide/pipelines/finetune_embeddings.py, llm-complete-guide/steps/distilabel_generate_queries.py, llm-complete-guide/steps/finetune_embeddings.py, llm-complete-guide/steps/hf_dataset_loader.py, llm-complete-guide/steps/push_to_argilla.py, llm-complete-guide/steps/push_to_hf.py
- resolve argilla default workspace warning
- add constants for re-usable variables
=> Various improvements

llm-lora-finetuning/pipelines/train_accelerated.py, llm-lora-finetuning/steps/__init__.py, llm-lora-finetuning/steps/finetune.py
Reworking a bit to follow the 0.65.0 syntax
=> fix for 0.65.0

README.md
Updated the links in the README.
=> Fix links in the README after projects -> products change

omni-reader/Dockerfile.sandbox, omni-reader/settings.json
This PR adds a `Dockerfile.sandbox` file for running the project within the VS Code sandbox environment. I created a basic `settings.json` file as well to auto-apply the dark theme mainly.
=> Add Dockerfile for running OmniReader in sandbox environment
