.codespell-ignore-words
.github/workflows/pull_request.yml
.typos.toml
zen-news-summarization/README.md

Switched out `codespelling` for `typos` so we have the same process on our main branches.

Standardise our spellchecking on CI

---

langchain-llamaindex-slackbot/README.md
langchain-llamaindex-slackbot/src/Dockerfile-slackbot
langchain-llamaindex-slackbot/src/local_testing_slackbot.py
langchain-llamaindex-slackbot/src/main.py
langchain-llamaindex-slackbot/src/pipelines/index_builder.py
langchain-llamaindex-slackbot/src/requirements-slackbot.txt
langchain-llamaindex-slackbot/src/requirements-zenml-io-qa.txt
langchain-llamaindex-slackbot/src/requirements.txt
langchain-llamaindex-slackbot/src/slackbot_utils.py
langchain-llamaindex-slackbot/src/steps/url_scraper.py
langchain-llamaindex-slackbot/src/zenbot_website.Dockerfile

- I split the Dockerfiles and the requirements.txt files into two, for each of our two bots
- I updated the core syntax where we query the client for the vector store to use the new post-execution syntax.
- Updated the README to reflect these changes.
- (Ran our formatting script which caught some things needing updating from previous PRs / commits)

Update / fix zenbot

---

langchain-llamaindex-slackbot/src/chat_lanarky.py
langchain-llamaindex-slackbot/src/main.py
langchain-llamaindex-slackbot/src/requirements-zenml-io-qa.txt

Also fixed some leftover dependency issues from #77.
(Also updated our GCP monitoring to check these endpoints once an hour + the connection to Discord where we receive these alerts).

Add healthcheck endpoints for both bots

---

langchain-llamaindex-slackbot/.gitignore
langchain-llamaindex-slackbot/src/local_testing_slackbot.py
langchain-llamaindex-slackbot/src/pipelines/index_builder.py
langchain-llamaindex-slackbot/src/requirements-slackbot.txt
langchain-llamaindex-slackbot/src/requirements-zenml-io-qa.txt
langchain-llamaindex-slackbot/src/steps/index_generator.py
langchain-llamaindex-slackbot/src/steps/url_scraper.py

For demo's I like running on vertex, so some requirements are needed in teh docker image. Also the open_api token is needed

Allow running on remote orchestrator

---

customer-satisfaction/README.md
customer-satisfaction/requirements.txt

Had a community hour call where packages weren't resolving, even with `uv`. I made these two changes and things resolved again. I haven't tested the pipeline, yet, but will do so before merging.

Relax dependencies for customer satisfaction project + update README

---

llm-lora-finetuning/lit_gpt/lora.py
llm-lora-finetuning/lit_gpt/model.py
llm-lora-finetuning/pipelines/evaluate.py
llm-lora-finetuning/pipelines/feature_engineering.py
llm-lora-finetuning/pipelines/finetuning.py
llm-lora-finetuning/pipelines/merge.py
llm-lora-finetuning/run.py
llm-lora-finetuning/steps/evaluate.py
llm-lora-finetuning/steps/feature_engineering.py
llm-lora-finetuning/steps/finetune.py
llm-lora-finetuning/steps/merge.py
llm-lora-finetuning/steps/utils.py

This pull request fixes some formatting issues in the code.

Format llm-lora project

---

llm-complete-guide/requirements.txt
llm-complete-guide/utils/llm_utils.py

This pull request adds reranking functionality to the retrieval process in order to improve the relevance of the retrieved documents. It includes the following commits:
- add reranking to inference
- make reranking optional
The changes in the code include modifications to the `process_input_with_retrieval` function, which now includes a `rerank_documents` function to rerank the retrieved documents based on the input query. The reranked documents are then used in the completion process.

Add reranking functionality to retrieval process

---

llm-lora-finetuning/configs/phi3_finetune.yaml
llm-lora-finetuning/requirements.txt

Added a config file for finetuning one of the phi-3 models. It requires `sentencepiece` to be present to load the tokenizer.

Add phi-3 FT config option for local finetune

---

llm-lora-finetuning/README.md
llm-lora-finetuning/configs/llama3-1_finetune_local.yaml
llm-lora-finetuning/configs/llama3-1_finetune_remote.yaml
llm-lora-finetuning/requirements.txt
llm-lora-finetuning/steps/evaluate_model.py
llm-lora-finetuning/steps/finetune.py

Add config and updates for Llama 3.1

---

huggingface-sagemaker/steps/deploying/sagemaker_deployment.py
huggingface-sagemaker/steps/promotion/promote_metric_compare_promoter.py
huggingface-sagemaker/steps/training/model_trainer.py

I updated the huggingface sagemaker example to get to a working stage.
- fix artifact logging function
- log additional metadata about the sagemaker endpoint
- start with a small deployment instance so we don't incur costs accidentally and can keep it running for demos. the new type is 300 times cheaper than the one before.
- fix types in the promotion pipeline

Fixes to the huggingface sagemaker example

---

llm-complete-guide/README.md
llm-complete-guide/configs/dev/rag.yaml
llm-complete-guide/constants.py
llm-complete-guide/deployment_hf.py
llm-complete-guide/gh_action_rag.py
llm-complete-guide/pipelines/__init__.py
llm-complete-guide/pipelines/finetune_embeddings.py
llm-complete-guide/pipelines/llm_basic_rag.py
llm-complete-guide/pipelines/llm_index_and_evaluate.py
llm-complete-guide/requirements.txt
llm-complete-guide/run.py
llm-complete-guide/steps/eval_e2e.py
llm-complete-guide/steps/eval_retrieval.py
llm-complete-guide/steps/eval_visualisation.py
llm-complete-guide/steps/finetune_embeddings.py
llm-complete-guide/steps/hf_dataset_loader.py
llm-complete-guide/steps/populate_index.py
llm-complete-guide/steps/rag_deployment.py
llm-complete-guide/steps/url_scraper.py
llm-complete-guide/steps/url_scraping_utils.py
llm-complete-guide/utils/llm_utils.py

Quite a few small fixes.
Also made Postgresql the default DB again.
And parallelise the evals.

Make `llm-complete-guide` work again

---

llm-agents/README.md
llm-complete-guide/deployment_hf.py
llm-complete-guide/steps/eval_langfuse.py

- Implement parallel processing for evaluation pairs and question-answer pairs
- Add ProgressTracker class to monitor and log evaluation progress
- Introduce configurable timeouts and worker count via environment variables
- Improve error handling and logging for parallel evaluation process
- Refactor fast_eval function to support concurrent execution and detailed tracking
Also:
- make the deployed app look nice again
- make it run a lot faster by a) setting `gpt-4o-mini` as the model to use and b) turning off reranking

Misc improvements

---

.typos.toml
research-radar/pipelines/classification.py

This updates the classification pipeline to replace dot notation (e.g. `config.datasets.unclassified`) with bracket notation (`config["datasets"]["unclassified"]`) to properly access values from the YAML configuration.

Fix research radar config

---

README.md

Small facelift for the project list. It felt a bit overcrowded with these `code` words in the previous iteration. Also made some other small nit / fixes while I was there.
Now it looks like this:
- Updated project list to include clearer domain and key features columns.
- Removed outdated references and improved the description of projects.
- Changed Python version requirement to >=3.9 for better compatibility.
- Removed the MLStacks link from the contributing section.

Update Project listing presentation

---

.github/workflows/build-push-codespace.yml

Force Docker to use the amd64 variant in our GitHub Actions workflow to fix the `no match for platform in manifest` error when pulling `zenml-sandbox:latest`.

Fix "no match for platform" GH action failure

---

.github/workflows/build-push-codespace.yml

Matrix picked up the top-level `scripts/ ` folder as a “project” and then tried to do:
```
docker buildx build --file scripts/Dockerfile.codespace …
```
This change excluds `scripts/`  from the `detect-changes` step

Stop GitHub Actions from trying to build scripts/Dockerfile.codespace

---

zenml-support-agent/README.md

**Problem**
Running the installation command from  `zenml-support-agent` fails.
```
$ pip install -r src/requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'src/requirements.txt'
```
This is because requirements is in the root directory and there is no `src` subdirectory.
**Solution**
Remove `src/` from the path.
**Alternative**
Create `src` directory, but I chose not to because all other directories except 1 have this file structure.

chore: update README.md of zenml-support-agent to correct installation path

---

README.md
huggingface-sagemaker/README.md
magic-photobooth/README.md
sign-language-detection-yolov5/README.md

- fix stack command typo in huggingface-sagemaker README
- correct project folder name in magic-photobooth README
- drop non-existent yolov5 requirements from sign language project
- update project table descriptions in root README
- `ruff check .` *(fails: unrecognized subcommand or lint issues)*

Fix README mismatches

---

deep_research/README.md
deep_research/requirements.txt
deep_research/utils/tracing_metadata_utils.py

- Add OPENROUTER_API_KEY documentation to README installation instructions
- Update litellm dependency to >=1.73.0 (remove upper bound constraint)  
- Update langfuse dependency to <3.0.0 for compatibility
- Fix import issues in tracing_metadata_utils.py

Fix imports and update dependencies

---

ADDING_PROJECTS.md
README.md

This commit introduces a new document, ADDING_PROJECTS.md, which outlines the requirements and steps for adding projects to the ZenML Projects repository. It includes details on necessary files, Docker configuration, backend integration, image requirements, and the deployment process, ensuring a comprehensive resource for contributors.
Please provide a short summary explaining the motivation behind these changes.
Please link to any relevant issues or discussions.

Add guide for adding projects to ZenML repository

---

qualityflow/README.md
qualityflow/pipelines/generate_and_evaluate.py
qualityflow/prompts/unit_test_strict_v2.jinja
qualityflow/prompts/unit_test_v1.jinja
qualityflow/requirements.txt
qualityflow/steps/analyze_code.py
qualityflow/steps/fetch_source.py
qualityflow/steps/gen_tests_agent.py
qualityflow/steps/report.py
qualityflow/steps/run_tests.py

Please provide a short summary explaining the motivation behind these changes.
Please link to any relevant issues or discussions.

Refactor test execution and coverage reporting
